@startmindmap

* key process patterns
** derive scope from goals
** specifying collaboratively
** illustrating using examples
** refinning the specification
** automating validation without changing specifications
** validating frequently

@endmindmap